# Generated by Django 4.2.1 on 2023-05-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_image', models.ImageField(upload_to='photos/album/')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('music_image', models.ImageField(upload_to='photos/music/')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('count', models.IntegerField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.album')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/playlist')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_image', models.ImageField(upload_to='photos/singer/')),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.music')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.user'),
        ),
        migrations.CreateModel(
            name='Favourite_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.music')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.album')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.user')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='singer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.singer'),
        ),
    ]
