# Generated by Django 4.2.1 on 2023-05-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='singer_id',
        ),
    ]
