# Generated by Django 4.2.1 on 2023-05-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0002_remove_album_singer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='album_id',
            new_name='album',
        ),
    ]
