# Generated by Django 4.2.1 on 2023-05-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0003_rename_album_id_music_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite_album',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='favourite_album',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='favourite_music',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='favourite_music',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='playlist_music',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='playlist_music',
            name='playlist_id',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Favourite_Album',
        ),
        migrations.DeleteModel(
            name='Favourite_Music',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='PlayList',
        ),
        migrations.DeleteModel(
            name='Playlist_Music',
        ),
    ]
