# Generated by Django 4.2.1 on 2023-05-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0007_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
