# Generated by Django 4.2.1 on 2023-05-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0011_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('music_image', models.ImageField(upload_to='photos/music/')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('music_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('count', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.album')),
            ],
        ),
    ]
