# Generated by Django 4.2.1 on 2023-05-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0012_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_length',
        ),
    ]
