# Generated by Django 4.2.1 on 2023-05-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0013_remove_music_music_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
