# Generated by Django 4.2.1 on 2023-05-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0018_rename_user_id_playlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='spotify_playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/spotify_playlist')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.music')),
                ('spotify_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.spotify_playlist')),
            ],
        ),
    ]
