# Generated by Django 4.2.1 on 2023-05-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0019_spotify_playlist_playlist_music'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlist_Music',
            new_name='spotify_playlist_Music',
        ),
    ]
