# Generated by Django 4.2.1 on 2023-05-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0020_rename_playlist_music_spotify_playlist_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.music')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.music')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.album')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify.user')),
            ],
        ),
    ]
