# Generated by Django 4.2.1 on 2023-05-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0021_playlist_music_favourite_music_favourite_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite_album',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='favourite_album',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favourite_music',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='favourite_music',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='playlist_music',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='playlist_music',
            old_name='playlist_id',
            new_name='playlist',
        ),
    ]
