# Generated by Django 4.2.1 on 2023-05-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0023_remove_favourite_music_music_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='spotify_playlist_Music',
        ),
    ]
