# Generated by Django 4.2.1 on 2023-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0026_spotify_playlist_spotify_playlist_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
