# Generated by Django 4.2.1 on 2023-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0028_music_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
