# Generated by Django 4.2.1 on 2023-05-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0030_music_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify_playlist',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/spotify_playlist'),
        ),
    ]
